repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Or latest version
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 24.4.2 # Or latest version
    hooks:
    -   id: black
        args: [--line-length=88]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4 # Or latest version for ruff
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix] # Auto-fix and fail if fixes were made
    -   id: ruff-format # If you want ruff to also format (can replace black for some)
        # args: []
